In [3]:
#create 2D array with ones
import numpy as np
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#using 2D array with ones
import numpy as np
arr=(3,4)
print(arr)

(3, 4)


In [5]:
#array with 6 ones and integer data type
import numpy as np
arr=np.ones((6,),dtype=int)
print(arr)

[1 1 1 1 1 1]


In [6]:
#use numpy.ones() where datatype is float
import numpy as np
arr=np.ones([4,3],dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
#create array with heterogeneous data types
import numpy as np
arr=np.ones((3,2),dtype=[('x','int'),('y','float')])
print(arr)

[[(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.)]]
