In [12]:
#slicing
import numpy as n
ar=n.array([1,20,5,9,3,4,8,5,6,2,25,2,2265,3,33])
slicing=ar[4:9]
print("New slicing ",slicing)
print("New array ",ar)
print(type(slicing))
print(type(ar))
slicing[:]=0
print("Old slicing ",slicing)
print("Old array ",ar)

New slicing  [3 4 8 5 6]
New array  [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Old slicing  [0 0 0 0 0]
Old array  [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]


In [14]:
#arange
import numpy as n
ar=n.arange(1,15)
print(ar)
print(ar[ar%2==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [15]:
#arange
import numpy as n
ar=n.arange(1,15)
print(ar)
print(ar[ar%2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[2 1 2 1 2 1 2 1 2 1 2 1 2 1]


In [17]:
#min,max,argmin,argmax,sqrt,sin,cos
import numpy as n
arr=n.array([10,20,30,25,6,2])
print(n.min(arr))
print(n.max(arr))
print(n.argmin(arr))
print(n.argmax(arr))
print(n.sqrt(arr))
print(n.sin(arr))
print(n.cos(arr))

2
30
5
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [22]:
#min,max,sum,cumsum in matrices
import numpy as n
n.random.seed(122)
mat=n.random.randint(1,21,9).reshape(3,3)
print(mat)
print(n.sum(mat))
print(n.cumsum(mat))
print(n.min(mat))
print(n.max(mat))
print("---------------")
print(n.sum(mat,axis=1))
print(n.min(mat,axis=1))
print(n.max(mat,axis=1))
print(n.cumsum(mat,axis=1))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
---------------
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


In [23]:
import numpy as n
n.random.seed(122)
mat=n.random.randint(1,21,10)
print(mat)
n.random.shuffle(mat)
print(mat)
print(n.unique(mat,return_index=True,return_counts=True))

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
