In [3]:
#numpy.zeros() with shape
import numpy as np
a=np.zeros((6,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
#numpy.zeros() without order
import numpy as np
a=np.zeros((6,),dtype=int)
print(a)

[0 0 0 0 0 0]


In [7]:
#numpy.zeros() without dtype and order
import numpy as np
a=np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]
