In [4]:
import numpy as np
l=[10,30,25,43,21]
arr=np.array(l)
print(arr)

[10 30 25 43 21]


In [7]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("a array",a)
print("b array",b)
print("c array",c)
print("d array",d)
print("a array dimen",a.ndim)
print("b array dimen",b.ndim)
print("c array dimen",c.ndim)
print("d array dimen",d.ndim)

a array 42
b array [1 2 3 4 5]
c array [[1 2 3]
 [4 5 6]]
d array [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
a array dimen 0
b array dimen 1
c array dimen 2
d array dimen 3


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
sarr=arr[1:5]
print(arr)
print(sarr)
sarr[2]=100
print(arr)
print(sarr)

[1 2 3 4 5 6 7]
[2 3 4 5]
[  1   2   3 100   5   6   7]
[  2   3 100   5]
